### ISSUE TITLE
Cmake installs unconditionally

### ISSUE THREAD

**Issue by SoilRos** [parafields/parafields-core#50]
When embedding the project with CMake's `FetchContent_Declare` and `FetchContent_Populate`, one may not want to install the underlining library as part of the parent project. For example:

```cmake
find_package(parafields QUIET)
# ... library not installed, we provide it from git
if (NOT parafields_FOUND)
  include(FetchContent)
  FetchContent_Declare(
    parafields
    GIT_REPOSITORY https://github.com/parafields/parafields-core.git
    GIT_TAG        3d711989be8f0838834f8c0667ae9b6af5061cbe
    )

  if(NOT parafields_POPULATED)
    FetchContent_Populate(parafields)
    add_subdirectory("${parafields_SOURCE_DIR}" "${parafields_BINARY_DIR}")
  endif()
endif()
```

This works fine, however, it will also install the contents of parafields unconditionally together with the parent project. In some cases this may not be wanted. For example, when using the library for tests, or for internal binaries.

Thus, I propose to opt out from the installation with a CMake option `INSTALL_PARAFIELDS` very much like in [gtest](https://github.com/google/googletest/blob/main/CMakeLists.txt#L20C16-L20C16).

**Comment by dokempf** [comment]
Implemented in #51. If you need a tag or release, please ping me.
